name: Module Twitch

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-18.04

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - id: get_version
        uses: battila7/get-version-action@v2

      - name: Install wine
        shell: bash
        run: |
          sudo dpkg --add-architecture i386
          wget -nc https://dl.winehq.org/wine-builds/winehq.key
          sudo apt-key add winehq.key
          sudo apt-add-repository 'deb https://dl.winehq.org/wine-builds/ubuntu/ bionic main'
          sudo apt update
          sudo apt install --install-recommends winehq-stable

      - name: Build
        shell: bash
        run: |
          yarn
          yarn build

      - name: Build & Pack Linux x64
        shell: bash
        run: |
          yarn build:x64:linux
          mv ./build/linux-x64/module-twitch ./build/linux-x64/${{ github.event.repository.name }}-linux-x64-${{ steps.get_version.outputs.version }}
          cd ./build/linux-x64/
          npx bestzip ../${{ github.event.repository.name }}-linux-x64-${{ steps.get_version.outputs.version }}.zip .

      - name: Build & Pack Win x64
        shell: bash
        run: |
          yarn build:x64:win
          mv ./build/win-x64/module-twitch.exe ./build/win-x64/${{ github.event.repository.name }}-win-x64-${{ steps.get_version.outputs.version }}.exe
          cd ./build/win-x64/
          npx bestzip ../${{ github.event.repository.name }}-win-x64-${{ steps.get_version.outputs.version }}.zip .

      - name: Build & Pack Macos x64
        shell: bash
        run: |
          yarn build:x64:macos
          mv ./build/macos-x64/module-twitch ./build/macos-x64/${{ github.event.repository.name }}-macos-x64-${{ steps.get_version.outputs.version }}
          cd ./build/macos-x64/
          npx bestzip ../${{ github.event.repository.name }}-macos-x64-${{ steps.get_version.outputs.version }}.zip .

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          files: |
            ./build/*.zip

      - name: Artifact Linux x64
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}-linux-x64-${{ steps.get_version.outputs.version }}
          path: ./build/linux-x64
          retention-days: 1

      - name: Artifact Win x64
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}-win-x64-${{ steps.get_version.outputs.version }}
          path: ./build/win-x64
          retention-days: 1

      - name: Artifact Macos x64
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}-macos-x64-${{ steps.get_version.outputs.version }}
          path: ./build/macos-x64
          retention-days: 1